# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-08-16 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_business_today', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HeadlineArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_stories_today', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LocalArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_local_today', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SportsArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_sports_today', models.TextField()),
            ],
        ),
    ]
