# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-09-04 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessarticle',
            name='second_community_story',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='businessarticle',
            name='third_community_story',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='localarticle',
            name='second_PandC_story',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='localarticle',
            name='third_PandC_story',
            field=models.TextField(blank=True),
        ),
    ]
